### ISSUE TITLE
Unexistent type annotator in Python 3.9 or lower produces crash

### ISSUE THREAD

**Issue by DiddiLeija** [HarshNarayanJha/Tic-Tac-Toe-with-AI#1]
Hi, first of all, congrats for this project, it has a great start!

I tried to run the game, using the instructions from the README, and I found this bug:

```
ImportError: cannot import name 'TypeAlias' from 'typing' (C:\Users\Diego Ramirez\AppData\Local\Programs\Python\Python39\lib\typing.py)
```

I'm using a virtualenv created with `python -m virtualenv`, Python 3.9 and a Windows machine.

Making a further investigation, `TypeAlias` is a Python 3.10+ feature (see https://docs.python.org/3/library/typing.html#typing.TypeAlias). You could provide an alternative to `TypeAlias` for Pythons lower than 3.10. Also, you may prefer to only support Python 3.10+, but to me, that could be a little uneffective.

I'm not sure if there're more features that crash with not-EOL'd Pythons, I haven't checked that yet.

**Comment by HarshNarayanJha** [comment]
It says that because I exclusively used Python 3.10 to get the advantage of using the TypeAlias annotation (and several other features) 
I think I was supposed to mention Python 3.10 and above, sorry, I will do it right now

**Comment by DiddiLeija** [comment]
Got it, thanks for clarifying!
